# Generated by Django 5.2.3 on 2025-06-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('distance_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
