# Generated by Django 5.1.3 on 2025-06-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='trail',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
