# Generated by Django 5.1.3 on 2025-06-28 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_trail_image_url_alter_trail_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='image',
        ),
        migrations.CreateModel(
            name='TrailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trail')),
            ],
        ),
    ]
