# Generated by Django 5.1.3 on 2025-06-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_trail_image_trailimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='distance_m',
            new_name='distance_km',
        ),
    ]
