# Generated by Django 5.2.3 on 2025-06-29 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_distance_m_trail_distance_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailimage',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.trail'),
        ),
    ]
